name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: AiScreenDev  # <-- your App Service name

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# GITHUB_TOKEN needs packages:write to push to GHCR (still log in with PAT below)
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase owner/repo for image path
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # Use a PAT with write:packages for the FIRST push (and generally reliable always)
      - name: Log in to GitHub Container Registry (PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push container image to GHCR
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
    environment:
      name: Development
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Lowercase owner/repo for image path
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{ env.REPO }}:${{ github.sha }}
