name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & tag (timestamp + latest)
      - name: Build image
        run: |
          IMAGE_NAME=docker.io/nidzam26/resume-evaluator
          TIMESTAMP=$(date +%s)

          docker build . -f Dockerfile \
            -t $IMAGE_NAME:$TIMESTAMP \
            -t $IMAGE_NAME:latest

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      # Push both tags
      - name: Push image
        run: |
          docker push $IMAGE_NAME:$TIMESTAMP
          docker push $IMAGE_NAME:latest
