name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and tag the Docker image; tag with both timestamp and 'latest'
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/${{ github.repository }}/my-image-name:$IMAGE_TAG \
          --tag ghcr.io/${{ github.repository }}/my-image-name:latest

    # Push the tags to registry
    - name: Push the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker push ghcr.io/${{ github.repository }}/my-image-name:$IMAGE_TAG
        docker push ghcr.io/${{ github.repository }}/my-image-name:latest
