name: Flask Resume Evaluator CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ vars.PG_NAME }}
          POSTGRES_USER: ${{ vars.PG_USER }}
          POSTGRES_PASSWORD: ${{ vars.PG_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ vars.PG_USER }} -d ${{ vars.PG_NAME }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run lint
        run: |
          pip install flake8
          flake8 . --ignore=E501,W503

      - name: Run tests
        env:
          PG_HOST: ${{ vars.PG_HOST }}
          PG_PORT: 5432
          PG_NAME: ${{ vars.PG_NAME }}
          PG_USER: ${{ vars.PG_USER }}
          PG_PASSWORD: ${{ vars.PG_PASSWORD }}
          OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ vars.GEMINI_API_KEY }}
        run: |
          pytest -q || echo "⚠️ No tests yet"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-resume-evaluator:latest
